name: 1.0$(rev:.r) # build numbering format

jobs:
  - job: "ContinuousIntegration"
    displayName: "Continuous Integration"
    pool:
      vmImage: "ubuntu-20.04"
    steps:
    - task: Npm@1
      displayName: 'Install NPM Packages'
      inputs:
        verbose: false
    - task: Npm@1
      displayName: 'Lint'
      inputs:
        command: custom
        verbose: false
        customCommand: 'run ng lint'
    - task: Npm@1
      displayName: 'npm audit'
      inputs:
        command: custom
        customCommand: 'audit --registry=https://registry.npmjs.org/'
    - task: Npm@1
      displayName: 'Build Application for Production'
      inputs:
        command: custom
        verbose: false
        customCommand: 'run ci-build-prod'
