name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
  pipelines:
    - pipeline: eafwebapp-release-pip # Name of the pipeline resource
      source: 02-EAFWebApp-Create-Artifacts # Name of the pipeline referenced by the pipeline resource
      trigger: true

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  
variables:
- group: DrMuellersExampleApp-Common
- group: DrMuellersExampleApp-Frontend

stages:
  - stage: Production
    displayName: "Production"
    jobs:
      - deployment: "DeploymentProduction"
        environment: "DrMuellersExampleApp-WebApp-Frontend"
        displayName: "Deployment Production"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: "Download Build Artifacts"
                inputs:
                  buildType: specific
                  project: 'ba9fa09c-552b-4c7d-ac6c-65c3351012f4'
                  pipeline: 226
                  specificBuildWithTriggering: true
                  downloadPath: '$(System.DefaultWorkingDirectory)/Artifacts'
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy Azure App Service'
                inputs:
                  azureSubscription: '05b34a60-79e8-4b91-ac72-afb66d4551c9'
                  appType: 'webApp'
                  WebAppName: 'DrMuellersExampleAppFrontend'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/Artifacts/drop'
                  JSONFiles: '**/*.json'