name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true # batch changes if true; start a new build for every push if false (default)
  branches:
    include:
      - refs/heads/master

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
  demands: npm

variables:
  BuildConfiguration: "Release"

steps:
  - template: StepTemplates/Initialize.yaml

  - task: Npm@1
    displayName: 'npm audit'
    inputs:
      command: custom
      customCommand: 'audit --registry=https://registry.npmjs.org/'

  - task: Npm@1
    displayName: "Lint"
    inputs:
      command: custom
      verbose: false
      customCommand: "run ci:lint"

  - task: Npm@1
    displayName: "Build"
    inputs:
      command: custom
      verbose: false
      customCommand: "run ci:build"