name: 1.0$(rev:.r) # build numbering format

trigger: none # will disable CI builds entirely

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
  demands: npm

resources:
  pipelines:
    - pipeline: eafwebapp-create-artifacts-pip # Name of the pipeline resource
      source: 01-EAFWebApp-Continuous-Integration # Name of the pipeline referenced by the pipeline resource
      trigger:
        branches:
          - refs/heads/master

jobs:
  - job: "BuildAndPublishAsArtifact"
    displayName: "Build and save zipped Artifact"
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest

    steps:
      - template: StepTemplates/Initialize.yaml

      - task: Npm@1
        displayName: "Build"
        inputs:
          command: custom
          verbose: false
          customCommand: "run ci:build"

      - task: qetza.replacetokens.replacetokens-task.replacetokens@5
        displayName: "Replace tokens in appsettings.json"
        inputs:
          rootDirectory: "$(Build.Repository.LocalPath)/dist"
          targetFiles: |
            **/appsettings.json
          tokenPattern: rm
          verbosity: detailed
          keepToken: true

      - task: PublishBuildArtifacts@1
        displayName: "Save unzipped Artifact"
        inputs:
          PathtoPublish: "$(Build.Repository.LocalPath)/dist"
